controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

app_bonjour:
    path: /bonjour/{abir}
    controller: App\Controller\HomoContollerController::bonjour
    #requirements:
    # name: '\d+'


